config/routes.rb
Rails.application.routes.draw do
  resources :users
  #root to:'users#index'
  get 'profile/profile'
  get 'post/post'
  get 'about/about'
  get 'home/home'
  get 'found/found'
  get 'find/find'
  get 'signup/signup'
  get 'lost/lost' 
  get 'welcome/index'
  root 'home#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/find_controller.rb
class FindController < ApplicationController
  def find
  end
end

app/controllers/found_controller.rb
class FoundController < ApplicationController
  def found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/lost_controller.rb
class LostController < ApplicationController
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def post
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def profile
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def signup
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :id_card, :phone, :username, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/found_helper.rb
module FoundHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lost_helper.rb
module LostHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :id_card
    = f.text_field :id_card
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
<main>
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Surname
      %th Id card
      %th Phone
      %th Username
      %th Password
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.surname
        %td= user.id_card
        %td= user.phone
        %td= user.username
        %td= user.password
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path
</main>

app/views/users/new.html.haml
<main>
<div align= "center">
%h1 - Register -

= render 'form'

-#= link_to 'Back', root_path
</div>
</main>