config/routes.rb
Rails.application.routes.draw do
  resources :users
  #root to:'users#index'
  get 'profile/profile'
  get 'post/post'
  get 'about/about'
  get 'home/home'
  get 'found/found'
  get 'find/find'
  get 'signup/signup'
  get 'lost/lost' 
  get 'welcome/index'
  root 'home#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

app/controllers/find_controller.rb
class FindController < ApplicationController
  def find
  end
end

app/controllers/found_controller.rb
class FoundController < ApplicationController
  def found
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/lost_controller.rb
class LostController < ApplicationController
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :id_card, :phone, :username, :password)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/find_helper.rb
module FindHelper
end

app/helpers/found_helper.rb
module FoundHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lost_helper.rb
module LostHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<head>
  <title>Lost Find Found Cat & Dog </title>
  <link href="https://fonts.googleapis.com/css?family=Itim&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="grid-container">
    <header>
        <img style="width: 100%;" src="/images/banner03.jpg" height="270px"/>
        <div class="tab" style="float: right;">
            <a class="btn-home">
                <img style="margin-right: 10px;" src="/images/home-icon-silhouette.png" height="20" width="20">
                <%= link_to "HOME", root_path,class: "btnTap" %>
            </a>
            <a class="btn-lost">
                <img style="margin-right: 10px;" src="/images/wanted.png" height="20" width="20">
                <%= link_to "LOST", lost_lost_path,class: "btnTap" %>
            </a>
            <a class="btn-find">
                <img style="margin-right: 10px;" src="/images/find.png" height="20" width="20">
                <%= link_to "FIND", find_find_path,class: "btnTap" %>
            </a>
            <a class="btn-found">
                <img style="margin-right: 10px;" src="/images/pawprint.png" height="20" width="20">
                <%= link_to "FOUND", found_found_path,class: "btnTap" %>
            </a>      
            <a class="btn-about">                   
                    <img style="margin-right: 10px;" src="/images/information.png" height="20" width="20">
                    <%= link_to "ABOUT", about_about_path,class: "btnTap" %>
            </a>
        </div>
    </header>

app/views/layouts/_menu.html.erb
<menu>
    	<div class="login">
    		<div style="padding-top: 15px">
    			<img src="/images/dog.png" height="42" width="42">
    			<img src="/images/cat.png" height="42" width="42">
    		</div>
    		<h1> Login </h1>
    		<div style="padding-bottom: 5px">
    		<img src="/images/user.png" height="" width="">
    		<label>
    			Username:
    		</label>
    	</div>
    	<div style="padding-bottom: 5px">
    		<input type="text" name = "username">
    	</div>
    	<div style="padding-bottom: 5px">
    		<img src="/images/lock.png" height="" width="">
    		<label>
    			Password:
    		</label>
    	</div>
    	<div style="padding-bottom: 5px">
    		<input type="text" name = "password">
    	</div>
    	<div class="">
    		<a class= "btn-login" href="profile/profile"><button type="button">Login</button></a>
    		<a class= "signup"><%= link_to "Sign up ?", new_user_path,class: "signup" %></a>
    	</div>
    	</div>	
</menu>

app/views/layouts/_profile.html.erb
<menu>
    
</menu>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= render 'layouts/menu'%>
    <%= yield %>
  </body>
</html>